baseurl = "https://studiozenkai.com"
languageCode = "en-us"
title = "Studio Zenkai"
twitter = "heri"
github = "heri"
flickr = "heri_quebec"
email = "heri@studiozenkai.com"
theme = "hugo-uno"
[params]
  author = "Heri"
  description = "Studio Zenkai is dedicated to the craft of programming, hardware hacking, photography, machine learning and how to live sensibly."